"""Adding skips column to StreamingMetrics

Revision ID: 22eac88e9d61
Revises: 12ade47eaa7f
Create Date: 2025-03-13 00:35:26.425918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22eac88e9d61'
down_revision = '12ade47eaa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skips', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saves', sa.Integer(), nullable=True))
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('saves')
        batch_op.drop_column('skips')

    # ### end Alembic commands ###
