"""Added likes, shares, and saves to StreamingMetrics

Revision ID: 8473e647b600
Revises: 22eac88e9d61
Create Date: 2025-03-13 01:14:43.785419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8473e647b600'
down_revision = '22eac88e9d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.drop_column('skips')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skips', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('likes')
        batch_op.drop_column('shares')

    # ### end Alembic commands ###
